MUSEI(NOME,CITTA)
ARTISTI(NOME,NAZIONE)
OPERE(CODICE,TITOLO,NOME_M,NOME_A)

SELECT 
FROM MUSEO M, OPERE O, ARTISTA A
WHERE 
GROUP BY M.NOME


ATTORI(COD,NOME,ANNO,NAZIONE)
RECITA(COD_ATTORE,COD_FILM)
FILM(COD,TITOLO,ANNO,NAZIONE,REGISTA,GENERE)
PROIEZIONI(COD,COD_FILM,COD_SALA,INCASSO,DATA_P)
SALE(COD,POSTI,NOME,CITTA)

/*10*/
SELECT F.COD
FROM FILM F, RECITA R
WHERE F.DOC=R.COD_FILM AND 'DE NIRO' = (SELECT ATTORI.NOME
										FROM  ATTORE A1
										WHERE A1.COD=R.COD_ATTORE 
                                        AND 'AL PACINO' = (SELECT F.COD
														   FROM ATTORE A2
													       WHERE A2.COD=R.COD_ATTORE)
                                                           
SELECT F.COD
FROM FILM F1, RECITA R1
WHERE F1.DOC=R1.COD_FILM AND EXISTS ( SELECT F.COD
									FROM FILM F2, RECITA R2, RECITA R3
									WHERE F2.COD=R2.COD_FILM AND 
                                                           
                                                           
SELECT COUNT(*)
FROM SALE S
WHERE S.CITTA='PISA'

/*19*/
SELECT F.TITOLO, SUM(P.INCASS), COUNT(*)
FROM FILM F, PROIEZIONI P,SALA S
WHERE F.COD=P.COD_FILM AND P.COD_SALA=S.COD AND S.CITTA='PISA' AND F.REGISTA='SPIELBERG'
GROUP BY FILM.TITOLO, P.INCASSO

/*20*/
SELECT F.REGISTA, A.NOME, COUNT(*) 
FROM FILM F, ATTORE A, RECITA R
WHERE F.COD=R.COD_FILM AND A.COD=R.COD_ATTORE
GROUP BY F.REGISTA, A.NOME

/*21*/
SELECT F.REGISTA, F,TITOLO 
FROM FILM F1, ATTORE A1, RECITA R1
WHERE F.COD=R.COD_FILM AND A.COD=R1.COD_ATTORE 
								AND 6>= (SELECT COUNT(DISTINCT R.COD_ATTORE)
										FROM  ATTORE A2, RECITA R2
										wHERE F.COD=R2.COD_FILM AND A2.COD=R2.COD_ATTORE)

/*22*/
SELECT P.TITOLO, P.COD, SUM(P.INCASSI) 
FROM FILM F, PROIEZIONE P
WHERE F.COD=P.COD_FILM AND F.ANNO>2000
GROUP BY P.TITOLO, P.COD

/*23*/
SELECT  COUNT(DISTINCT R1.COD_ATTORE) 
FROM FILM F1, RECITA R1
WHERE F1.COD=R1.COD_FILM 
GROUP BY R1.COD_FILM
HAVING  R1.COD_FILM NOT IN  (SELECT R2.COD_FILM
							FROM  RECITA R2, ATTORI A1
							WHERE R2.COD_ATTORE=A1.COD AND A1.ANNO>=1970) 

/*24*/
SELECT P.TITOLO, P.COD, SUM(P.INCASSI) 
FROM FILM F, PROIEZIONE P
WHERE F.COD=P.COD_FILM AND F.GENERE='SCI-FI'
GROUP BY P.TITOLO, P.COD

/*27*/
SELECT S.NOME, P.COD, SUM(P.INCASSI) 
FROM  PROIEZIONE P,SALA S
WHERE S.COD=P.COD_SALA AND S.CITTA='PISA'AND P.DATA_P='01/01/01'
GROUP BY S.NOME, P.COD_SLA
HAVING SUM(P.INCASSI)>2000

/*28*/
SELECT F.NOME 
FROM  PROIEZIONE P,SALA S
WHERE S.COD=P.COD_SALA AND S.CITTA='PISA'AND P.DATA_P='01/01/01'
GROUP BY S.CITTA, F.NOME
HAVING S.CITTA<>'PISA'

/*28*/
SELECT F.NOME 
FROM  FILM F1,PROIEZIONE P1
WHERE F1.COD=P1.COD_SALA NOT EXISTS (SELECT *
									FROM  PROIEZIONE P2, PROIEZIONE P3, SALA S
									WHERE P2.COD_FILM=F1.COD AND P3.COD_SALA=S.COD AND P2.COD_FILM=P3.COD_FILM AND S.CITTA='PISA')

/*29*/                                   
SELECT F.NOME 
FROM  FILM F1,PROIEZIONE P1
WHERE F1.COD=P1.COD_SALA NOT EXISTS (SELECT *
									FROM  PROIEZIONE P2, SALA S1, SALA S2
									WHERE P2.COD_FILM=F1.COD AND )
                                    
/*30*/                                   
SELECT F.NOME 
FROM  FILM F1,PROIEZIONE P1
WHERE F1.COD=P1.COD_SALA NOT EXISTS (SELECT *
									FROM  PROIEZIONE P2
									WHERE P2.COD_FILM=F1.COD AND 500 >= ALL ((SELECT *
																			FROM  PROIEZIONE P3
																			WHERE P3.COD_FILM=F1.COD)
									)										

/*31*/                                   
SELECT F.NOME 
FROM  FILM F1
WHERE 500 <= (SELECT P.INCASSO
			  FROM  PROIEZIONE P2
			  WHERE P2.COD_FILM=F1.COD )
              
/*32*/                                   
SELECT A.NOME 
FROM  ATTORI A1, PROIEZIONI P1
WHERE A.NAZIONE='ITALIA' AND A1.COD=P1.COD_ATTORE NOT EXISTS (SELECT *
			  FROM   RECITA P2, FILM F1
			  WHERE A1.COD=P2.COD_ATTORE AND P2.COD_FILM=F1.COD AND F1.REGISTA='FELLINI' )
              
 /*33*/                                   
SELECT A.NOME 
FROM  ATTORE A, RECITA R1
WHERE AND A.NAZIONE='ITALIA' AND A1.COD=R1.COD_ATTORE AND R1.COD_FILM NOT IN ( SELECT P1.COD_FILM 
											FROM  PROIEZIONI P1, FILM F
											WHERE  A.COD=P1.COD_ATTORE AND F.REGSITA='FELLINI')         

/*35*/                                   
SELECT A.NOME 
FROM  ATTORE A, RECITA R1
WHERE AND  A1.COD=R1.COD_ATTORE AND P1.COD_FILM IN ( SELECT P1.COD_FILM 
											FROM  PROIEZIONI P1, FILM F
											WHERE  A.COD=P1.COD_ATTORE AND F.ANNO=1960 AND F.REGSITA='FELLINI')

/*36*/                                   
SELECT A.NOME 
FROM  ATTORE A, RECITA R1
WHERE AND  A1.COD=R1.COD_ATTORE AND P1.COD_FILM IN ( SELECT P1.COD_FILM 
											FROM  PROIEZIONI P1, FILM F
											WHERE  A.COD=P1.COD_ATTORE AND F.ANNO=1960 AND F.REGSITA='FELLINI')